//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseStudentMaps = new HashSet<CourseStudentMap>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Capacity { get; set; }
        public double Cost { get; set; }
        public int Enroll { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<CourseStudentMap> CourseStudentMaps { get; set; }
    }
}
